server:
  port: 9000

spring:
  application:
    name: monitor
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123456
  boot:  # 不显示的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}